// Type declarations for @liquicode/jsonstor-mongodb
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored on a MongoDB server.

declare module '@liquicode/jsonstor-mongodb'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** The MongoDB connection string, e.g. `mongodb://localhost`. */
		ConnectionString: string;
		/** The name of the database to use. */
		DatabaseName: string;
		/** The name of the collection to use. */
		CollectionName: string;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** `'jsonstor-mongodb'`. The package's bare name, which `Aliases` maps onto a prime. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
		/** This package's prime versions, each registering under its own name. */
		Adapters: StorageAdapter[];
		/** Every other name this package answers to, mapped to the prime it resolves to. */
		Aliases: { [ AliasName: string ]: string };
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-mongodb.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];
	export const Adapters: StorageAdapter[ 'Adapters' ];
	export const Aliases: StorageAdapter[ 'Aliases' ];

}
